version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_BASE_URL=http://localhost:3000
    env_file:
      - .env
    command: pnpm run dev
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
